### PR TITLE
ci: add LICENSE

### PR DESCRIPTION
**Pull request by spacewander**
I found this project doesn't have a LICENSE yet.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>

### CODE REVIEW

**Comment by soulbird** [comment]
Do workflows also need a LICENSE?

**Comment by spacewander** [comment]
Some projects add licenses in workflows, like:
https://github.com/apache/skywalking-banyandb/blob/main/.github/workflows/ci.yml

If you don't like this setting, we can remove it.

**Comment by soulbird** [comment]
> Some projects add licenses in workflows, like: https://github.com/apache/skywalking-banyandb/blob/main/.github/workflows/ci.yml
> 
> If you don't like this setting, we can remove it.

Just curious because you just removed the license at: https://github.com/api7/wasm-nginx-module/pull/135

**Comment by soulbird** [comment]
Let's be consistent with APISIX, no license

**Review by soulbird — APPROVED** [review]

**Pull request merged**
